// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluepktxmglffrkllwpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdWVwa3R4bWdsZmZya2xsd3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTU4NTAsImV4cCI6MjA2NTEzMTg1MH0.LEKCy3YPfcLR3iquU8-U6jU-lz7DT8Cr-im1GDqq6d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);